#!/usr/bin/env node
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../../..");
const descriptor = JSON.parse(readFileSync(resolve(root, "protocol/embedded.json"), "utf8"));
const surface = JSON.parse(readFileSync(resolve(root, "protocol/embedded.surface.json"), "utf8"));
const { blob, surface: wireSurface } = validateDescriptor(descriptor, surface);
const id = contractId(descriptor);
const update = process.argv.includes("--update");
const sourceMutation = readSourceMutation();
const browser = validateSemanticDescriptor("browser", browserSurface());
const mobile = validateSemanticDescriptor("mobile", mobileSurface());
const storage = validateSemanticDescriptor("storage", storageSurface());
const browserId = contractId(browser);
const mobileId = contractId(mobile);
const storageId = contractId(storage);
const outputs = new Map([
  [
    resolve(root, "packages/embedded/src/contract/generated.ts"),
    `// Generated by packages/embedded/scripts/contract.mjs. Do not edit.\nexport const CURRENT_WIRE_CONTRACT_ID = ${JSON.stringify(id)} as const;\nexport const WIRE_BLOB_CHUNK_BYTES = ${blob.chunkBytes};\nexport const WIRE_BLOB_CLIENT_SCOPE_LIMIT = ${blob.clientScopes};\nexport const WIRE_BLOB_CLIENT_BYTE_LIMIT = ${blob.clientBytes};\nexport const WIRE_SURFACE = ${JSON.stringify(wireSurface, null, 2)} as const;\nexport const WIRE_ERROR_PROTOCOL_MISMATCH = WIRE_SURFACE.errors[0];\nexport type WireContractId = typeof CURRENT_WIRE_CONTRACT_ID;\n`,
  ],
  [
    resolve(root, "crates/storage/src/contract/generated.rs"),
    `// Generated by packages/embedded/scripts/contract.mjs. Do not edit.\npub const CURRENT_WIRE_CONTRACT_ID: &str =\n    ${JSON.stringify(id)};\npub const CURRENT_MOBILE_BRIDGE_CONTRACT_ID: &str =\n    ${JSON.stringify(mobileId)};\npub const CURRENT_STORAGE_BINDING_CONTRACT_ID: &str =\n    ${JSON.stringify(storageId)};\npub const WIRE_BLOB_CHUNK_BYTES: usize = ${rustInteger(blob.chunkBytes)};\npub const WIRE_BLOB_CLIENT_SCOPE_LIMIT: usize = ${rustInteger(blob.clientScopes)};\npub const WIRE_BLOB_CLIENT_BYTE_LIMIT: usize = ${rustInteger(blob.clientBytes)};\npub const WIRE_ENDPOINT_PULL: &str = ${JSON.stringify(wireSurface.endpoints.pull)};\npub const WIRE_ENDPOINT_PUSH: &str = ${JSON.stringify(wireSurface.endpoints.push)};\npub const WIRE_ENDPOINT_UPLOAD: &str = ${JSON.stringify(wireSurface.endpoints.upload)};\n`,
  ],
  [
    resolve(root, "packages/embedded/src/browser/coordinator/contract.ts"),
    `// Generated by packages/embedded/scripts/contract.mjs. Do not edit.\nexport const CURRENT_BROWSER_COORDINATION_CONTRACT_ID = ${JSON.stringify(browserId)} as const;\n`,
  ],
  [
    resolve(root, "packages/embedded/src/expo/contract.ts"),
    `// Generated by packages/embedded/scripts/contract.mjs. Do not edit.\nexport const CURRENT_MOBILE_BRIDGE_CONTRACT_ID = ${JSON.stringify(mobileId)} as const;\nexport const CURRENT_WIRE_CONTRACT_ID = ${JSON.stringify(id)} as const;\n`,
  ],
  [
    resolve(root, "packages/embedded/src/storage/contract.ts"),
    `// Generated by packages/embedded/scripts/contract.mjs. Do not edit.\nexport const CURRENT_STORAGE_BINDING_CONTRACT_ID = ${JSON.stringify(storageId)} as const;\n`,
  ],
]);
const check = process.argv.includes("--check");
let changed = false;
const changedPaths = [];
for (const [path, content] of outputs) {
  let existing = "";
  try {
    existing = readFileSync(path, "utf8");
  } catch {}
  if (!generatedEqual(path, existing, content)) {
    changed = true;
    changedPaths.push(path);
    if (!check) writeFileSync(path, content);
  }
}
if (!check && changed) {
  execFileSync("vp", ["fmt", ...[...outputs.keys()].filter((path) => path.endsWith(".ts"))], {
    cwd: root,
    stdio: "inherit",
  });
}
if (check && changed) {
  console.error(`Generated contract drift: ${changedPaths.join(", ")}`);
  process.exitCode = 1;
}

function canonicalJson(value) {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  return `{${Object.keys(value)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`)
    .join(",")}}`;
}

/** Format generated integer literals to satisfy Rust's readability lint. */
function rustInteger(value) {
  if (!Number.isSafeInteger(value) || value < 0) {
    throw new Error(`Expected a non-negative safe integer, received ${value}`);
  }
  return value.toLocaleString("en-US").replaceAll(",", "_");
}

function readDescriptor(name) {
  const value = JSON.parse(readFileSync(resolve(root, `protocol/${name}.json`), "utf8"));
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`protocol/${name}.json must be an object`);
  }
  if (typeof value.format !== "string" || !value.format.startsWith("convex-embedded-")) {
    throw new Error(`protocol/${name}.json must declare a Convex Embedded format`);
  }
  return value;
}

/**
 * The three local contracts deliberately derive their identities from the source that defines
 * their ABI. A short hand-written list is not a compatibility boundary: it inevitably misses
 * optional fields, nested worker frames, or one of the native operations.  Instead, TypeScript's
 * own parser prints the declaration closure rooted at each public boundary.  The closure follows
 * imported project declarations, which makes a change to (for example) WorkerRequest part of the
 * browser coordination identity without duplicating that type here.
 */
function validateSemanticDescriptor(name, semanticSurface) {
  const value = readDescriptor(name);
  const pointer = value.surface;
  if (!pointer || typeof pointer !== "object" || Array.isArray(pointer)) {
    throw new Error(`protocol/${name}.json must declare its generated semantic surface`);
  }
  if (pointer.algorithm !== "semantic-source/v2") {
    if (!update) {
      throw new Error(`protocol/${name}.json surface algorithm must be semantic-source/v2`);
    }
    pointer.algorithm = "semantic-source/v2";
  }
  const digest = `sha256:${createHash("sha256").update(canonicalJson(semanticSurface)).digest("hex")}`;
  if (pointer.digest !== digest) {
    if (!update) {
      throw new Error(
        `protocol/${name}.json semantic surface changed; run node packages/embedded/scripts/contract.mjs --update to record ${digest}`,
      );
    }
    pointer.digest = digest;
    writeFileSync(resolve(root, `protocol/${name}.json`), `${JSON.stringify(value, null, 2)}\n`);
  }
  return value;
}

function browserSurface() {
  return {
    format: "convex-embedded-browser-semantic-surface/v1",
    declarations: typescriptDeclarations([
      {
        file: "packages/embedded/src/browser/coordinator/protocol.ts",
        names: [
          "ControlOp",
          "PeerOp",
          "RejectCode",
          "ControlMessage",
          "PeerMessage",
          "isControlMessage",
          "isPeerMessage",
          "isForeignCoordinationFrame",
        ],
      },
    ]),
    implementation: implementationSources([
      "config/epoch.json",
      "packages/embedded/src/browser/coordinator.ts",
      "packages/embedded/src/browser/coordinator",
      "packages/embedded/src/browser/identity.ts",
      "packages/embedded/src/browser/protocol.ts",
    ]),
  };
}

function mobileSurface() {
  const typescriptOperations = operationsIn(
    "packages/embedded/src/expo/store.ts",
    /this\.invoke(?:Remote)?(?:<[^>]+>)?\(\s*"([A-Za-z][A-Za-z0-9]*)"/g,
  );
  const rustOperations = operationsIn(
    "crates/mobile/src/lib.rs",
    /^\s*(?:operation\s*@\s*)?\(?((?:"[A-Za-z][A-Za-z0-9]*"\s*\|\s*)*"[A-Za-z][A-Za-z0-9]*")\)?\s*=>/gm,
    (match) => [...match[1].matchAll(/"([A-Za-z][A-Za-z0-9]*)"/g)].map((value) => value[1]),
  );
  const ts = new Set(typescriptOperations);
  const rust = new Set(rustOperations);
  if (ts.size !== rust.size || [...ts].some((operation) => !rust.has(operation))) {
    throw new Error(
      `mobile bridge operation mismatch: TypeScript=[${sortStrings([...ts]).join(",")}] Rust=[${sortStrings([...rust]).join(",")}]`,
    );
  }
  return {
    format: "convex-embedded-mobile-semantic-surface/v1",
    declarations: typescriptDeclarations([
      {
        file: "packages/embedded/src/expo/codec.ts",
        names: [
          "NativeEnvelope",
          "NativeResponse",
          "encodeRequest",
          "decodeRequest",
          "decodeResponse",
          "encodeMessage",
          "decodeMessage",
        ],
      },
      {
        file: "packages/embedded/src/expo/module.ts",
        names: ["NativeStoreObject", "NativeModule", "createNativeModuleLoader"],
      },
      { file: "packages/embedded/src/expo/store.ts", names: ["ExpoStoreBinding"] },
    ]),
    operations: sortStrings([...ts]),
    markers: markersIn("packages/embedded/src/expo/codec.ts"),
    implementation: implementationSources([
      "config/epoch.json",
      "packages/embedded/src/expo",
      "crates/mobile/include",
      "crates/mobile/src",
      "packages/embedded/android/src",
      "packages/embedded/ios",
    ]),
  };
}

function storageSurface() {
  return {
    format: "convex-embedded-storage-semantic-surface/v1",
    declarations: typescriptDeclarations([
      { file: "packages/embedded/src/storage/binding.ts", names: ["StoreBinding"] },
      { file: "packages/embedded/src/node/artifact.ts", names: ["NativeModule"] },
      { file: "packages/embedded/src/browser/artifact.ts", names: ["WasmModule"] },
    ]),
    implementation: implementationSources([
      "config/epoch.json",
      "crates/storage/build.rs",
      "packages/embedded/src/browser/artifact.ts",
      "packages/embedded/src/browser/opfs.ts",
      "packages/embedded/src/node",
      "packages/embedded/src/storage",
      "crates/node/src",
      "crates/storage/src",
    ]),
  };
}

/**
 * @param {string} file
 * @param {RegExp} pattern
 * @param {(match: RegExpMatchArray) => string[]} [map]
 * @returns {string[]}
 */
function operationsIn(file, pattern, map = (match) => [match[1]]) {
  const values = new Set();
  for (const match of sourceText(file).matchAll(pattern)) {
    for (const value of map(match)) values.add(value);
  }
  return sortStrings([...values]);
}

/** @param {string[]} values */
function sortStrings(values) {
  return values.sort((left, right) => left.localeCompare(right));
}

function markersIn(file) {
  const source = sourceText(file);
  const values = [];
  for (const name of ["BUFFER", "FLOAT", "INTEGER"]) {
    const match = source.match(new RegExp(`const ${name} = "([^"\\n]+)";`));
    if (!match) throw new Error(`mobile codec marker ${name} is missing`);
    values.push(match[1]);
  }
  return values;
}

/**
 * Every authored file under a boundary root participates. Generated contract constants are
 * deliberately excluded: including an ID in the source used to compute that ID would make the
 * descriptor recursive. TypeScript is canonicalized through its parser and Rust through rustfmt.
 * Swift, Kotlin, and C have no parser in this build toolchain, so their exact source is a
 * deliberate conservative input: comment or formatting edits rotate the affected native ABI ID
 * rather than risking an unsound normalization.
 */
function implementationSources(roots) {
  const ts = readTypeScript();
  const files = new Set();
  for (const entry of roots) collectSourceFiles(resolve(root, entry), files);
  return [...files]
    .sort((left, right) => left.localeCompare(right))
    .map((file) => ({ file, source: canonicalSource(file, ts) }));
}

function collectSourceFiles(path, files) {
  let entries;
  try {
    entries = readdirSync(path, { withFileTypes: true });
  } catch {
    if (!/\.(?:h|json|kt|rs|swift|ts)$/.test(path)) {
      throw new Error(`contract implementation root is missing: ${path}`);
    }
    const relative = path.slice(`${root}/`.length);
    if (!isGeneratedSource(sourceText(relative))) files.add(relative);
    return;
  }
  for (const entry of entries) {
    const child = resolve(path, entry.name);
    if (entry.isDirectory()) collectSourceFiles(child, files);
    else if (entry.isFile() && /\.(?:h|json|kt|rs|swift|ts)$/.test(entry.name)) {
      const relative = child.slice(`${root}/`.length);
      if (!isGeneratedSource(sourceText(relative))) files.add(relative);
    }
  }
}

function isGeneratedSource(source) {
  return source.startsWith("// Generated by packages/embedded/scripts/contract.mjs.");
}

function canonicalSource(file, ts) {
  const source = sourceText(file);
  if (file.endsWith(".json")) return canonicalJson(JSON.parse(source));
  if (file.endsWith(".ts")) {
    const parsed = ts.createSourceFile(file, source, ts.ScriptTarget.ESNext, false);
    return ts
      .createPrinter({ newLine: ts.NewLineKind.LineFeed, removeComments: true })
      .printFile(parsed);
  }
  if (file.endsWith(".rs")) {
    return execFileSync("rustfmt", ["--emit", "stdout", "--edition", "2021"], {
      encoding: "utf8",
      input: source,
    });
  }
  return source;
}

function readSourceMutation() {
  const index = process.argv.indexOf("--test-source-mutation");
  if (index < 0) return undefined;
  const [file, before, after] = process.argv.slice(index + 1, index + 4);
  if (!file || before === undefined || after === undefined) {
    throw new Error("--test-source-mutation needs <file> <before> <after>");
  }
  return { after, before, file };
}

function sourceText(file) {
  const source = readFileSync(resolve(root, file), "utf8");
  if (!sourceMutation || sourceMutation.file !== file) return source;
  if (!source.includes(sourceMutation.before)) {
    throw new Error(`test source mutation did not match ${file}`);
  }
  return source.replace(sourceMutation.before, sourceMutation.after);
}

function typescriptDeclarations(entries) {
  const ts = readTypeScript();
  const paths = entries.map(({ file }) => resolve(root, file));
  const program = ts.createProgram(paths, {
    allowJs: false,
    noEmit: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.ESNext,
  });
  const checker = program.getTypeChecker();
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed, removeComments: true });
  const rootPrefix = `${root}/`;
  const projectSource = (node) => node.getSourceFile().fileName.startsWith(rootPrefix);
  const declarations = new Map();
  const visited = new Set();

  const addSymbol = (symbol) => {
    if (!symbol) return;
    if (symbol.flags & ts.SymbolFlags.Alias) symbol = checker.getAliasedSymbol(symbol);
    const key = `${symbol.name}:${symbol.declarations?.[0]?.getSourceFile().fileName}:${symbol.declarations?.[0]?.pos}`;
    if (visited.has(key)) return;
    visited.add(key);
    for (const declaration of symbol.declarations ?? []) {
      if (!projectSource(declaration)) continue;
      const file = declaration.getSourceFile();
      const relative = file.fileName.slice(rootPrefix.length);
      const printed = printer.printNode(ts.EmitHint.Unspecified, declaration, file);
      declarations.set(`${relative}:${declaration.pos}`, {
        file: relative,
        kind: ts.SyntaxKind[declaration.kind],
        text: printed,
      });
      visitTypeReferences(declaration);
    }
  };
  const visitTypeReferences = (node) => {
    const visit = (child) => {
      if (
        ts.isTypeReferenceNode(child) ||
        ts.isExpressionWithTypeArguments(child) ||
        ts.isTypeQueryNode(child)
      ) {
        const name = ts.isTypeQueryNode(child)
          ? child.exprName
          : (child.expression ?? child.typeName);
        addSymbol(checker.getSymbolAtLocation(name));
      }
      ts.forEachChild(child, visit);
    };
    ts.forEachChild(node, visit);
  };
  for (const { file, names } of entries) {
    const source = program.getSourceFile(resolve(root, file));
    if (!source) throw new Error(`contract source ${file} was not loaded`);
    for (const name of names) {
      const declaration = source.statements.find(
        (statement) =>
          (ts.isClassDeclaration(statement) ||
            ts.isFunctionDeclaration(statement) ||
            ts.isInterfaceDeclaration(statement) ||
            ts.isTypeAliasDeclaration(statement) ||
            ts.isVariableStatement(statement)) &&
          declarationName(ts, statement) === name,
      );
      if (!declaration) throw new Error(`contract declaration ${name} is missing from ${file}`);
      addSymbol(checker.getSymbolAtLocation(declarationNameNode(ts, declaration)));
    }
  }
  return [...declarations.values()].sort((left, right) =>
    `${left.file}:${left.text}`.localeCompare(`${right.file}:${right.text}`),
  );
}

function declarationName(ts, declaration) {
  return declarationNameNode(ts, declaration)?.text;
}

function declarationNameNode(ts, declaration) {
  if (ts.isVariableStatement(declaration)) return declaration.declarationList.declarations[0]?.name;
  return declaration.name;
}

function readTypeScript() {
  const store = resolve(root, "node_modules/.pnpm");
  const packages = readdirSync(store)
    .filter((entry) => entry.startsWith("typescript@"))
    .sort();
  // Vite+ currently compiles this repository with TypeScript 6. Keep the semantic printer on
  // that same compiler until TypeScript 7's compiler API is part of our supported toolchain.
  const packageDir =
    packages.filter((entry) => entry.startsWith("typescript@6.")).at(-1) ?? packages.at(-1);
  if (!packageDir)
    throw new Error("TypeScript is required to derive contract surfaces; run vp install");
  return createRequire(resolve(store, packageDir, "node_modules/typescript/package.json"))(
    "typescript",
  );
}

function contractId(value) {
  return `sha256:${createHash("sha256").update(canonicalJson(value)).digest("hex")}`;
}

function generatedEqual(path, left, right) {
  if (!path.endsWith(".ts")) return left === right;
  return normalizeGeneratedTypescript(left) === normalizeGeneratedTypescript(right);
}

function normalizeGeneratedTypescript(source) {
  return source
    .replace(/"([A-Za-z_$][A-Za-z0-9_$]*)":/g, "$1:")
    .replace(/\s+/g, "")
    .replace(/,([}\]])/g, "$1");
}

function validateDescriptor(value, surface) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error("protocol/embedded.json must be an object");
  }
  const pointer = value.surface;
  if (typeof pointer !== "object" || pointer === null || Array.isArray(pointer)) {
    throw new Error("protocol/embedded.json must point to its validator surface");
  }
  if (pointer.path !== "protocol/embedded.surface.json") {
    throw new Error("protocol/embedded.json surface path is invalid");
  }
  const surfaceDigest = `sha256:${createHash("sha256").update(canonicalJson(surface)).digest("hex")}`;
  if (pointer.digest !== surfaceDigest) {
    throw new Error(
      `protocol validator surface changed; update protocol/embedded.json surface digest to ${surfaceDigest}`,
    );
  }
  validateSurface(surface);
  const blob = value.blob;
  if (typeof blob !== "object" || blob === null || Array.isArray(blob)) {
    throw new Error("protocol/embedded.json must define a blob object");
  }
  const integer = (field) => {
    const candidate = blob[field];
    if (!Number.isSafeInteger(candidate) || candidate <= 0) {
      throw new Error(`protocol/embedded.json blob.${field} must be a positive safe integer`);
    }
    return candidate;
  };
  const chunkBytes = integer("chunkBytes");
  const clientScopes = integer("clientScopes");
  const clientBytes = integer("clientBytes");
  if (clientBytes < chunkBytes) {
    throw new Error("protocol/embedded.json blob.clientBytes must cover one chunk");
  }
  return { blob: { chunkBytes, clientScopes, clientBytes }, surface };
}

function validateSurface(surface) {
  if (typeof surface !== "object" || surface === null || Array.isArray(surface)) {
    throw new Error("protocol/embedded.surface.json must be an object");
  }
  if (surface.format !== "convex-embedded-wire-surface/v1") {
    throw new Error("protocol/embedded.surface.json has an unsupported format");
  }
  const endpoints = surface.endpoints;
  if (typeof endpoints !== "object" || endpoints === null || Array.isArray(endpoints)) {
    throw new Error("protocol validator surface must define endpoints");
  }
  for (const [name, expected] of Object.entries({
    pull: "embedded:pull",
    push: "embedded:push",
    upload: "embedded:upload",
  })) {
    if (endpoints[name] !== expected)
      throw new Error(`protocol endpoint ${name} must be ${expected}`);
  }
  for (const group of ["pull", "push"]) {
    if (typeof surface[group] !== "object" || surface[group] === null) {
      throw new Error(`protocol validator surface must define ${group} variants`);
    }
    for (const [kind, variant] of Object.entries(surface[group])) {
      if (typeof variant !== "object" || variant === null || !Array.isArray(variant.fields)) {
        throw new Error(`protocol ${group}.${kind} must define fields`);
      }
      const fields = variant.fields;
      if (
        fields.some((field) => typeof field !== "string") ||
        new Set(fields).size !== fields.length
      ) {
        throw new Error(`protocol ${group}.${kind} fields must be unique strings`);
      }
    }
  }
  if (
    !Array.isArray(surface.upload?.fields) ||
    !Array.isArray(surface.errors) ||
    typeof surface.validators !== "object" ||
    surface.validators === null ||
    Array.isArray(surface.validators)
  ) {
    throw new Error("protocol validator surface must define upload fields, errors, and validators");
  }
  for (const name of [
    "pullArgs",
    "pushArgs",
    "uploadArgs",
    "pullReturns",
    "pushReturns",
    "uploadReturns",
  ]) {
    if (!/^sha256:[0-9a-f]{64}$/.test(surface.validators[name] ?? "")) {
      throw new Error(`protocol validator surface validators.${name} must be a SHA-256 digest`);
    }
  }
}
