// Generated by packages/embedded/scripts/contract.mjs. Do not edit.
export const CURRENT_MOBILE_BRIDGE_CONTRACT_ID =
  "sha256:e2f7d5fce6a0e3e68146278f01f9878590a1980e659cca66cc1d0a78014c3a03" as const;
export const CURRENT_WIRE_CONTRACT_ID =
  "sha256:25671eb9dbef4d1038d3765159931e07aeaceee16afc82166e6b6bd5937d7a65" as const;
