// @estifanos-sh/convex-embedded-generated {"formatVersion":4,"manifestHash":"e1fc6cb81424bb37","schemaSourceHash":"beb27cf4db2bf389"}
/* eslint-disable */
// Generated by @estifanos-sh/convex-embedded. Do not edit.

import { defineLocal } from "@estifanos-sh/convex-embedded/internal/local";
import schema from "./schema.js";

export const embeddedGeneratedFormatVersion = 4 as const;
export const embeddedGeneratedIdentity = {
  formatVersion: 4,
  manifestHash: "e1fc6cb81424bb37",
  schemaSourceHash: "beb27cf4db2bf389",
} as const;
export const embeddedManifest = {
  documents: {
    read: {
      kind: "query",
      placement: "replicated",
      visibility: "public",
    },
    write: {
      kind: "mutation",
      placement: "replicated",
      visibility: "public",
    },
    del: {
      kind: "mutation",
      placement: "replicated",
      visibility: "public",
    },
    summaries: {
      kind: "query",
      placement: "replicated",
      visibility: "public",
    },
  },
  files: {
    generateUploadUrl: {
      kind: "mutation",
      placement: "replicated",
      visibility: "public",
    },
    metadata: {
      kind: "query",
      placement: "replicated",
      visibility: "public",
    },
    url: {
      kind: "query",
      placement: "replicated",
      visibility: "public",
    },
  },
  remote: {
    history: {
      kind: "query",
      placement: "remote",
      visibility: "public",
    },
    restore: {
      kind: "mutation",
      placement: "remote",
      visibility: "public",
    },
  },
} as const;

export const local = defineLocal(schema);
