// Generated by packages/embedded/scripts/contract.mjs. Do not edit.
export const CURRENT_STORAGE_BINDING_CONTRACT_ID =
  "sha256:a6d2017217660a6f7a97b2ecfeafb605007c24496be3441c47db6332e30e1454" as const;
