[workspace]
resolver = "2"
members = ["crates/storage", "crates/remote", "crates/node"]
exclude = ["vendor/convex"]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
perf = { level = "deny", priority = -1 }
let_underscore_must_use = "deny"
# Pedantic noise we don't care about.
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
cast_precision_loss = "allow"
cast_possible_wrap = "allow"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.release-wasm]
inherits = "release"
opt-level = "z"

[patch.crates-io]
convex = { path = "vendor/convex" }
