import path from "node:path";

import { withEmbeddedComponentTables, type EmbeddedSchemaAnalysis } from "../schema";
import type { StoreSchema } from "../storage/types";
import type { EmbeddedBundleResult } from "./index";

export const EMBEDDED_GENERATED_FORMAT_VERSION = 3;

const SCHEMA_SPECIFIER_EXTENSION = /\.([mc]?)(?:tsx?|jsx?)$/;

export interface EmbeddedGeneratedSchema extends EmbeddedSchemaAnalysis {
  runtimeStoreSchema: StoreSchema;
}

export interface EmbeddedGeneratedIdentity {
  formatVersion: number;
  manifestHash: string;
  schemaSourceHash: string;
}

/** The placement-aware device schema every bundler adapter inlines into its registry. */
export function toEmbeddedGeneratedSchema(
  analysis: EmbeddedSchemaAnalysis,
): EmbeddedGeneratedSchema {
  return { ...analysis, runtimeStoreSchema: withEmbeddedComponentTables(analysis.storeSchema) };
}

/**
 * Renders the checked-in placement lockfile: identity hashes plus the function manifest the
 * deployment enforces. The device schema stays out of it and is inlined by the registry instead.
 * When the bundle registers its schema, the lockfile also carries the `Register` augmentation
 * that binds the `local` builders to the schema's device data model.
 */
export function renderEmbeddedGenerated(bundle: EmbeddedBundleResult): string {
  const identity: EmbeddedGeneratedIdentity = {
    formatVersion: EMBEDDED_GENERATED_FORMAT_VERSION,
    manifestHash: bundle.manifestHash,
    schemaSourceHash: bundle.schemaSourceHash,
  };
  const header = `// @convex-dev/embedded-generated ${JSON.stringify(identity)}
/* eslint-disable */
// Generated by @convex-dev/embedded. Do not edit.
`;
  const values = `export const embeddedGeneratedFormatVersion = ${EMBEDDED_GENERATED_FORMAT_VERSION} as const;
export const embeddedGeneratedIdentity = ${JSON.stringify(identity)} as const;
export const embeddedManifest = ${JSON.stringify(bundle.manifest)} as const;
`;
  if (!bundle.registerSchema) return `${header}\n${values}`;
  const relative = path
    .relative(path.dirname(bundle.generatedPath), bundle.schemaPath)
    .split(path.sep)
    .join("/")
    .replace(SCHEMA_SPECIFIER_EXTENSION, ".$1js");
  const specifier = relative.startsWith(".") ? relative : `./${relative}`;
  return `${header}
import type {} from "@convex-dev/embedded/local";
import type schema from "${specifier}";

${values}
declare module "@convex-dev/embedded/local" {
  interface Register {
    schema: typeof schema;
  }
}
`;
}
