import { withEmbeddedComponentTables, type EmbeddedSchemaAnalysis } from "../schema";
import type { StoreSchema } from "../storage/types";
import type { EmbeddedBundleResult } from "./index";

export const EMBEDDED_GENERATED_FORMAT_VERSION = 2;

export interface EmbeddedGeneratedSchema extends EmbeddedSchemaAnalysis {
  runtimeStoreSchema: StoreSchema;
}

export interface EmbeddedGeneratedIdentity {
  formatVersion: number;
  manifestHash: string;
  schemaSourceHash: string;
}

/** The placement-aware device schema every bundler adapter inlines into its registry. */
export function toEmbeddedGeneratedSchema(
  analysis: EmbeddedSchemaAnalysis,
): EmbeddedGeneratedSchema {
  return { ...analysis, runtimeStoreSchema: withEmbeddedComponentTables(analysis.storeSchema) };
}

/**
 * Renders the checked-in placement lockfile: identity hashes plus the function manifest the
 * deployment enforces. The device schema stays out of it and is inlined by the registry instead.
 */
export function renderEmbeddedGenerated(bundle: EmbeddedBundleResult): string {
  const identity: EmbeddedGeneratedIdentity = {
    formatVersion: EMBEDDED_GENERATED_FORMAT_VERSION,
    manifestHash: bundle.manifestHash,
    schemaSourceHash: bundle.schemaSourceHash,
  };
  return `// @convex-dev/embedded-generated ${JSON.stringify(identity)}
/* eslint-disable */
// Generated by @convex-dev/embedded. Do not edit.

export const embeddedGeneratedFormatVersion = ${EMBEDDED_GENERATED_FORMAT_VERSION} as const;
export const embeddedGeneratedIdentity = ${JSON.stringify(identity)} as const;
export const embeddedManifest = ${JSON.stringify(bundle.manifest)} as const;
`;
}
