import path from "node:path";

import { withEmbeddedComponentTables, type EmbeddedSchemaAnalysis } from "../schema";
import type { StoreSchema } from "../storage/types";
import type { EmbeddedBundleResult } from "./index";

export const EMBEDDED_GENERATED_FORMAT_VERSION = 4;

const SCHEMA_SPECIFIER_EXTENSION = /\.([mc]?)(?:tsx?|jsx?)$/;

export interface EmbeddedGeneratedSchema extends EmbeddedSchemaAnalysis {
  runtimeStoreSchema: StoreSchema;
}

export interface EmbeddedGeneratedIdentity {
  formatVersion: number;
  manifestHash: string;
  schemaSourceHash: string;
}

/** The placement-aware device schema every bundler adapter inlines into its registry. */
export function toEmbeddedGeneratedSchema(
  analysis: EmbeddedSchemaAnalysis,
): EmbeddedGeneratedSchema {
  return { ...analysis, runtimeStoreSchema: withEmbeddedComponentTables(analysis.storeSchema) };
}

/**
 * Renders the checked-in Embedded contract: identity hashes, the function manifest enforced by
 * deployment, and the app-bound local function builders. The device storage schema stays out of
 * the contract and is inlined by the virtual registry instead.
 */
export function renderEmbeddedGenerated(bundle: EmbeddedBundleResult): string {
  const identity: EmbeddedGeneratedIdentity = {
    formatVersion: EMBEDDED_GENERATED_FORMAT_VERSION,
    manifestHash: bundle.manifestHash,
    schemaSourceHash: bundle.schemaSourceHash,
  };
  const header = `// @estifanos-sh/convex-embedded-generated ${JSON.stringify(identity)}
/* eslint-disable */
// Generated by @estifanos-sh/convex-embedded. Do not edit.
`;
  const values = `export const embeddedGeneratedFormatVersion = ${EMBEDDED_GENERATED_FORMAT_VERSION} as const;
export const embeddedGeneratedIdentity = ${renderGeneratedLiteral(identity)} as const;
export const embeddedManifest = ${renderGeneratedLiteral(bundle.manifest)} as const;
`;
  const relative = path
    .relative(path.dirname(bundle.generatedPath), bundle.schemaPath)
    .split(path.sep)
    .join("/")
    .replace(SCHEMA_SPECIFIER_EXTENSION, ".$1js");
  const specifier = relative.startsWith(".") ? relative : `./${relative}`;
  return `${header}
import { defineLocal } from "@estifanos-sh/convex-embedded/internal/local";
import schema from "${specifier}";

${values}
export const local = defineLocal(schema);
`;
}

function renderGeneratedLiteral(value: unknown, indentation = 0): string {
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const nested = indentation + 2;
    return `[\n${value
      .map((entry) => `${" ".repeat(nested)}${renderGeneratedLiteral(entry, nested)},`)
      .join("\n")}\n${" ".repeat(indentation)}]`;
  }
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value);
    if (entries.length === 0) return "{}";
    const nested = indentation + 2;
    return `{\n${entries
      .map(([key, entry]) => {
        const name = /^[$A-Z_a-z][$\w]*$/.test(key) ? key : JSON.stringify(key);
        return `${" ".repeat(nested)}${name}: ${renderGeneratedLiteral(entry, nested)},`;
      })
      .join("\n")}\n${" ".repeat(indentation)}}`;
  }
  return JSON.stringify(value) ?? "null";
}
