// @estifanos-sh/convex-embedded-generated {"formatVersion":4,"manifestHash":"44136fa355b3678a","schemaSourceHash":"beb27cf4db2bf389"}
/* eslint-disable */
// Generated by @estifanos-sh/convex-embedded. Do not edit.

import { defineLocal } from "@estifanos-sh/convex-embedded/internal/local";
import schema from "./schema.js";

export const embeddedGeneratedFormatVersion = 4 as const;
export const embeddedGeneratedIdentity = {
  formatVersion: 4,
  manifestHash: "44136fa355b3678a",
  schemaSourceHash: "beb27cf4db2bf389",
} as const;
export const embeddedManifest = {} as const;

export const local = defineLocal(schema);
