// Generated by packages/embedded/scripts/contract.mjs. Do not edit.
export const CURRENT_BROWSER_COORDINATION_CONTRACT_ID =
  "sha256:83d1b1e252bd43fedd4aeafd63ff759baacf299c5a4c0031108415c2523be3da" as const;
