// @convex-dev/embedded-generated {"formatVersion":4,"manifestHash":"44136fa355b3678a","schemaSourceHash":"beb27cf4db2bf389"}
/* eslint-disable */
// Generated by @convex-dev/embedded. Do not edit.

import { defineLocal } from "@convex-dev/embedded/internal/local";
import schema from "../schema.js";

export const embeddedGeneratedFormatVersion = 4 as const;
export const embeddedGeneratedIdentity = {
  formatVersion: 4,
  manifestHash: "44136fa355b3678a",
  schemaSourceHash: "beb27cf4db2bf389",
} as const;
export const embeddedManifest = {} as const;

export const local = defineLocal(schema);
