[package]
name = "node"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
napi = { version = "2", features = ["napi6", "async"] }
napi-derive = "2"
storage = { path = "../storage" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["sync"] }

[build-dependencies]
napi-build = "2"
