import type { RuntimeIdentity } from "./protocol";
import { browserStorageId } from "./storage";
import { WASM_API_VERSION } from "./artifact";
import { EMBEDDED_STORE_FORMAT_VERSION } from "../abi";
import { EMBEDDED_PROTOCOL_VERSION } from "../protocol";

/**
 * Replaced with the real package version at build time (see `tsdown.config.ts` `define`). Falls
 * back to "0.0.0" in unbundled/test contexts where the define is absent.
 */
declare const __EMBEDDED_PACKAGE_VERSION__: string | undefined;
const PACKAGE_VERSION =
  typeof __EMBEDDED_PACKAGE_VERSION__ === "string" ? __EMBEDDED_PACKAGE_VERSION__ : "0.0.0";
let embeddedIdentity:
  | {
      moduleGraphHash: string;
      schemaHash: string;
    }
  | undefined;

/**
 * Installs the virtual-module identity generated by the bundler adapter.
 *
 * @internal
 */
export function setEmbeddedIdentity(identity: {
  moduleGraphHash: string;
  schemaHash: string;
}): void {
  embeddedIdentity = {
    moduleGraphHash: identity.moduleGraphHash,
    schemaHash: identity.schemaHash,
  };
}

/**
 * Builds the browser runtime identity.
 *
 * @internal
 */
export function createRuntimeIdentity(storageId = browserStorageId()): RuntimeIdentity {
  if (!embeddedIdentity) {
    throw new Error(
      "ConvexEmbeddedClient requires the @convex-dev/embedded Vite or unplugin adapter to provide runtime identity.",
    );
  }
  return {
    moduleGraphHash: embeddedIdentity.moduleGraphHash,
    packageVersion: PACKAGE_VERSION,
    protocolVersion: EMBEDDED_PROTOCOL_VERSION,
    schemaHash: embeddedIdentity.schemaHash,
    storageId,
    storeFormatVersion: EMBEDDED_STORE_FORMAT_VERSION,
    wasmAbiVersion: WASM_API_VERSION,
  };
}

/**
 * Stable coordination scope for one origin storage runtime.
 *
 * The scope is intentionally protocol/package/storage/ABI scoped, not schema or module-graph
 * scoped. A schema/module mismatch must hit the same leader and be rejected there; otherwise two
 * different bundles could open separate OPFS database owners.
 *
 * @internal
 */
export function runtimeScope(identity: RuntimeIdentity): string {
  return [
    "convex-embedded",
    `p${identity.protocolVersion}`,
    `pkg${safe(identity.packageVersion)}`,
    `s${safe(identity.storageId)}`,
    `wasm${identity.wasmAbiVersion}`,
  ].join(":");
}

/**
 * Checks that a client can attach to this runtime.
 *
 * @internal
 */
export function assertSameRuntimeIdentity(
  actual: RuntimeIdentity,
  expected: RuntimeIdentity,
): void {
  const mismatches = (Object.keys(expected) as Array<keyof RuntimeIdentity>).filter(
    (key) => actual[key] !== expected[key],
  );
  if (!mismatches.length) return;
  throw new RuntimeIdentityMismatchError(mismatches);
}

/** An existing storage owner was opened by a different app deployment. @internal */
export class RuntimeIdentityMismatchError extends Error {
  constructor(readonly mismatches: Array<keyof RuntimeIdentity>) {
    const fields = mismatches.map(identityFieldLabel).join(", ");
    super(
      `Another tab is running a different version of this embedded app (${fields}). Close or reload all tabs for this site, then reopen the app.`,
    );
    this.name = "ConvexEmbeddedDeploymentMismatchError";
  }
}

function identityFieldLabel(field: keyof RuntimeIdentity): string {
  if (field === "moduleGraphHash") return "app code";
  if (field === "schemaHash") return "schema";
  if (field === "packageVersion") return "package";
  if (field === "protocolVersion") return "protocol";
  if (field === "wasmAbiVersion") return "WASM runtime";
  if (field === "storeFormatVersion") return "store format";
  return "storage";
}

function safe(value: string): string {
  return value.replace(/[^0-9A-Z_a-z.-]/g, "_");
}
