import type { RuntimeIdentity } from "./protocol";
import { browserStorageId } from "./storage";
import { CURRENT_STORAGE_BINDING_CONTRACT_ID } from "../storage/contract";
import { EMBEDDED_STORE_EPOCH } from "../abi";
import { CURRENT_WIRE_CONTRACT_ID } from "../protocol";

/**
 * Replaced with the real package version at build time (see `tsdown.config.ts` `define`). Falls
 * back to "0.0.0" in unbundled/test contexts where the define is absent.
 */
declare const __EMBEDDED_PACKAGE_VERSION__: string | undefined;
const PACKAGE_VERSION =
  typeof __EMBEDDED_PACKAGE_VERSION__ === "string" ? __EMBEDDED_PACKAGE_VERSION__ : "0.0.0";
let embeddedIdentity:
  | {
      moduleGraphHash: string;
      schemaHash: string;
    }
  | undefined;

/**
 * Installs the virtual-module identity generated by the bundler adapter.
 *
 * @internal
 */
export function setEmbeddedIdentity(identity: {
  moduleGraphHash: string;
  schemaHash: string;
}): void {
  embeddedIdentity = {
    moduleGraphHash: identity.moduleGraphHash,
    schemaHash: identity.schemaHash,
  };
}

/**
 * Builds the browser runtime identity.
 *
 * @internal
 */
export function createRuntimeIdentity(storageId = browserStorageId()): RuntimeIdentity {
  if (!embeddedIdentity) {
    throw new Error(
      "ConvexEmbeddedClient requires the @estifanos-sh/convex-embedded Vite or unplugin adapter to provide runtime identity.",
    );
  }
  return {
    moduleGraphHash: embeddedIdentity.moduleGraphHash,
    packageVersion: PACKAGE_VERSION,
    contractId: CURRENT_WIRE_CONTRACT_ID,
    schemaHash: embeddedIdentity.schemaHash,
    storageId,
    // This is the published storage-contract epoch, including candidate migrations. It remains
    // part of admission even though physical ownership is keyed only by the OPFS store address.
    storeFormatVersion: EMBEDDED_STORE_EPOCH,
    storageBindingId: CURRENT_STORAGE_BINDING_CONTRACT_ID,
  };
}

/**
 * Stable coordination scope for one origin storage runtime.
 *
 * The scope is only the physical storage address. Compatibility belongs to admission after the
 * owner has been found; adding a package, protocol, ABI, schema, or graph identity here would let
 * two incompatible bundles acquire independent owners for the same OPFS database.
 *
 * @internal
 */
export function runtimeScope(identity: RuntimeIdentity): string {
  return ["convex-embedded", "storage", safe(identity.storageId)].join(":");
}

/**
 * Checks that a client can attach to this runtime.
 *
 * @internal
 */
export function assertSameRuntimeIdentity(
  actual: RuntimeIdentity,
  expected: RuntimeIdentity,
): void {
  // These are the admission contract, not the owner address. Keep this list explicit so a setup
  // supplied by only one contender is a mismatch in both directions rather than being skipped by
  // Object.keys(expected).
  const mismatches = runtimeIdentityFields.filter((key) => actual[key] !== expected[key]);
  if (!mismatches.length) return;
  throw new RuntimeIdentityMismatchError(mismatches);
}

const runtimeIdentityFields = [
  "moduleGraphHash",
  "packageVersion",
  "contractId",
  "schemaHash",
  "setupGraphHash",
  "setupReference",
  "storeFormatVersion",
  "storageBindingId",
] as const satisfies ReadonlyArray<keyof RuntimeIdentity>;

/** An existing storage owner was opened by a different app deployment. @internal */
export class RuntimeIdentityMismatchError extends Error {
  constructor(readonly mismatches: Array<keyof RuntimeIdentity>) {
    const fields = mismatches.map(identityFieldLabel).join(", ");
    super(
      `Another tab is running a different version of this embedded app (${fields}). Close or reload all tabs for this site, then reopen the app.`,
    );
    this.name = "ConvexEmbeddedDeploymentMismatchError";
  }
}

function identityFieldLabel(field: keyof RuntimeIdentity): string {
  if (field === "moduleGraphHash") return "app code";
  if (field === "schemaHash") return "schema";
  if (field === "setupGraphHash" || field === "setupReference") return "setup action";
  if (field === "packageVersion") return "package";
  if (field === "contractId") return "protocol";
  if (field === "storageBindingId") return "storage runtime";
  if (field === "storeFormatVersion") return "store format";
  return "storage";
}

function safe(value: string): string {
  return value.replace(/[^0-9A-Z_a-z.-]/g, "_");
}
