// Generated by packages/embedded/scripts/contract.mjs. Do not edit.
pub const CURRENT_WIRE_CONTRACT_ID: &str =
    "sha256:25671eb9dbef4d1038d3765159931e07aeaceee16afc82166e6b6bd5937d7a65";
pub const CURRENT_MOBILE_BRIDGE_CONTRACT_ID: &str =
    "sha256:e2f7d5fce6a0e3e68146278f01f9878590a1980e659cca66cc1d0a78014c3a03";
pub const CURRENT_STORAGE_BINDING_CONTRACT_ID: &str =
    "sha256:a6d2017217660a6f7a97b2ecfeafb605007c24496be3441c47db6332e30e1454";
pub const WIRE_BLOB_CHUNK_BYTES: usize = 196_608;
pub const WIRE_BLOB_CLIENT_SCOPE_LIMIT: usize = 16;
pub const WIRE_BLOB_CLIENT_BYTE_LIMIT: usize = 8_388_608;
pub const WIRE_ENDPOINT_PULL: &str = "embedded:pull";
pub const WIRE_ENDPOINT_PUSH: &str = "embedded:push";
pub const WIRE_ENDPOINT_UPLOAD: &str = "embedded:upload";
