/**
 * Unplugin adapter for embedded Convex browser builds.
 *
 * @remarks
 * Use this entrypoint when integrating with bundlers through unplugin directly.
 * Vite/Vite+ users should prefer `@convex-dev/embedded/vite`, which also
 * installs the headers required by the browser WASM storage backend.
 *
 * @example
 * ```ts
 * import { convexEmbeddedUnplugin } from "@convex-dev/embedded/unplugin";
 *
 * export default {
 *   plugins: [convexEmbeddedUnplugin.rollup()],
 * };
 * ```
 *
 * @packageDocumentation
 */
import path from "node:path";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";

import { createUnplugin, type UnpluginInstance } from "unplugin";

import {
  createEmbeddedBundle,
  type EmbeddedBundleInput,
  type EmbeddedBundleResult,
} from "./bundler";

/**
 * Options for embedded Convex bundler adapters.
 *
 * @remarks
 * `convexDir` and `schemaPath` are resolved by the bundler adapter relative to
 * the bundler project root.
 *
 * @public
 */
export interface ConvexEmbeddedPluginOptions extends Omit<EmbeddedBundleInput, "root"> {
  /**
   * Disable the plugin. Useful when composing framework configs conditionally.
   *
   * @defaultValue `false`
   */
  disabled?: boolean;
}

/**
 * Supported unplugin adapter methods exposed by the embedded Convex plugin.
 *
 * @public
 */
export type ConvexEmbeddedUnplugin = Pick<
  UnpluginInstance<ConvexEmbeddedPluginOptions | undefined>,
  "esbuild" | "rollup" | "rolldown" | "rspack" | "vite" | "webpack"
>;

/**
 * Root virtual module generated by the embedded Convex bundler plugin.
 *
 * @internal
 */
export const VIRTUAL_MODULE_ID = "virtual:convex-embedded";

/**
 * Virtual module containing the embedded runtime identity.
 *
 * @internal
 */
export const VIRTUAL_IDENTITY_MODULE_ID = "virtual:convex-embedded/identity";

/**
 * Prefix for virtual modules that proxy real Convex source files.
 *
 * @internal
 */
export const VIRTUAL_SOURCE_MODULE_PREFIX = `${VIRTUAL_MODULE_ID}/source/`;
const RESOLVED_VIRTUAL_MODULE_ID = `\0${VIRTUAL_MODULE_ID}`;
const RESOLVED_VIRTUAL_IDENTITY_MODULE_ID = `\0${VIRTUAL_IDENTITY_MODULE_ID}`;
const DEFAULT_CONVEX_DIR = "convex";
const TS_EXTENSIONS = /\.(?:ts|tsx|mts|cts)$/;

const unplugin = createUnplugin((rawOptions?: ConvexEmbeddedPluginOptions) => {
  const options = rawOptions ?? {};
  let root = process.cwd();

  const convexRoot = (): string => path.resolve(root, options.convexDir ?? DEFAULT_CONVEX_DIR);

  return {
    name: "convex-embedded",
    enforce: "pre" as const,

    async resolveId(id, importer) {
      if (options.disabled) return null;
      if (id === VIRTUAL_MODULE_ID) return RESOLVED_VIRTUAL_MODULE_ID;
      if (id === VIRTUAL_IDENTITY_MODULE_ID) return RESOLVED_VIRTUAL_IDENTITY_MODULE_ID;
      const sourcePath = fromVirtualSourceId(id);
      if (sourcePath !== undefined) {
        const allowed = await sourceFiles({
          convexDir: options.convexDir,
          root,
          schemaPath: options.schemaPath,
        });
        return allowed.has(sourcePath) ? sourcePath : null;
      }
      if (
        (importer === RESOLVED_VIRTUAL_MODULE_ID ||
          importer === RESOLVED_VIRTUAL_IDENTITY_MODULE_ID) &&
        path.resolve(id) === convexRoot()
      ) {
        return path.resolve(convexRoot(), options.schemaPath ?? "schema.ts");
      }
      return null;
    },

    async load(this: { addWatchFile?: (id: string) => void }, id) {
      if (options.disabled) return null;
      if (id !== RESOLVED_VIRTUAL_MODULE_ID && id !== RESOLVED_VIRTUAL_IDENTITY_MODULE_ID) {
        return null;
      }
      const bundle = await createEmbeddedBundle({
        convexDir: options.convexDir,
        root,
        schemaPath: options.schemaPath,
      });
      this.addWatchFile?.(convexRoot());
      for (const file of watchFiles(bundle)) this.addWatchFile?.(file);
      if (id === RESOLVED_VIRTUAL_MODULE_ID) return renderEmbeddedBundle(bundle);
      if (id === RESOLVED_VIRTUAL_IDENTITY_MODULE_ID) return renderEmbeddedIdentity(bundle);
      return null;
    },

    vite: {
      configResolved(config) {
        root = config.root;
      },
      configureServer(server) {
        if (!options.disabled) server.watcher.add(convexRoot());
      },
      handleHotUpdate(ctx) {
        if (options.disabled || !isConvexSource(ctx.file, convexRoot())) return;
        const virtualModule = ctx.server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID);
        const identityModule = ctx.server.moduleGraph.getModuleById(
          RESOLVED_VIRTUAL_IDENTITY_MODULE_ID,
        );
        const invalidated = [virtualModule, identityModule].filter(
          (module) => module !== undefined,
        );
        for (const module of invalidated) ctx.server.moduleGraph.invalidateModule(module);
        return invalidated.length ? [...ctx.modules, ...invalidated] : undefined;
      },
    },

    webpack(compiler) {
      root = compiler.context || root;
    },

    rspack(compiler) {
      root = compiler.context || root;
    },
  };
});

/**
 * Unplugin instance for embedded Convex module discovery.
 *
 * @remarks
 * Call the adapter method for the bundler you are integrating with, such as
 * `convexEmbeddedUnplugin.rollup()` or `convexEmbeddedUnplugin.webpack()`.
 *
 * @public
 */
export const convexEmbeddedUnplugin = unplugin as ConvexEmbeddedUnplugin;

/**
 * Alias for {@link convexEmbeddedUnplugin}.
 *
 * @public
 */
export const convexEmbedded = convexEmbeddedUnplugin;
export default convexEmbeddedUnplugin;

/**
 * Encodes a real Convex source file as a virtual source module ID.
 *
 * @param filePath - Absolute or relative source file path.
 * @returns A virtual source module ID that the plugin can decode.
 *
 * @internal
 */
export function toVirtualSourceId(filePath: string): string {
  return `${VIRTUAL_SOURCE_MODULE_PREFIX}${Buffer.from(path.resolve(filePath), "utf8").toString(
    "base64url",
  )}`;
}

/**
 * Decodes a virtual source module ID into the real source path it should resolve to.
 *
 * @param id - Virtual source module ID.
 * @returns The decoded absolute source path, or `undefined` when `id` is not a
 * valid embedded source module ID.
 *
 * @internal
 */
export function fromVirtualSourceId(id: string): string | undefined {
  if (!id.startsWith(VIRTUAL_SOURCE_MODULE_PREFIX)) return undefined;
  const encoded = id.slice(VIRTUAL_SOURCE_MODULE_PREFIX.length);
  try {
    const decoded = Buffer.from(encoded, "base64url").toString("utf8");
    return path.isAbsolute(decoded) ? path.normalize(decoded) : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Renders the root `virtual:convex-embedded` registry as plain ESM.
 *
 * @param bundle - Discovered Convex schema and source module files.
 * @returns JavaScript source for the generated root virtual module.
 *
 * @internal
 */
export function renderEmbeddedBundle(bundle: EmbeddedBundleResult): string {
  const moduleEntries = Object.entries(bundle.modules)
    .map(
      ([moduleId, filePath]) =>
        `  ${objectKey(moduleId)}: () => import(${JSON.stringify(toVirtualSourceId(filePath))}),`,
    )
    .join("\n");

  return `import schema from ${JSON.stringify(toVirtualSourceId(bundle.schemaPath))};

export { schema };
export const modules = {
${moduleEntries}
};
`;
}

/**
 * Renders the lightweight embedded runtime identity virtual module.
 *
 * @param bundle - Discovered Convex schema and source module files.
 * @returns JavaScript source for the generated identity virtual module.
 *
 * @internal
 */
export async function renderEmbeddedIdentity(bundle: EmbeddedBundleResult): Promise<string> {
  const schemaHash = await fileHash(bundle.schemaPath);
  const moduleGraphHash = await hashJson(
    Object.fromEntries(
      await Promise.all(
        Object.entries(bundle.modules).map(async ([moduleId, filePath]) => [
          moduleId,
          await fileHash(filePath),
        ]),
      ),
    ),
  );

  return `export const embeddedIdentity = ${JSON.stringify({
    moduleGraphHash,
    schemaHash,
  })};
`;
}

function watchFiles(bundle: EmbeddedBundleResult): string[] {
  return [bundle.schemaPath, ...Object.values(bundle.modules)];
}

async function sourceFiles(input: EmbeddedBundleInput): Promise<Set<string>> {
  const bundle = await createEmbeddedBundle(input);
  return new Set(watchFiles(bundle).map((file) => path.normalize(file)));
}

function isConvexSource(file: string, convexDir: string): boolean {
  const resolved = path.resolve(file);
  if (!isInside(resolved, convexDir)) return false;
  if (!TS_EXTENSIONS.test(resolved)) return false;
  if (/\.d\.(?:ts|mts|cts)$/.test(resolved)) return false;
  return path
    .relative(convexDir, resolved)
    .split(path.sep)
    .every((part) => part !== "_generated");
}

function isInside(file: string, dir: string): boolean {
  const relative = path.relative(dir, file);
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

function objectKey(value: string): string {
  return /^[$A-Z_a-z][$\w]*$/.test(value) ? value : JSON.stringify(value);
}

async function fileHash(filePath: string): Promise<string> {
  return hash(await readFile(filePath));
}

async function hashJson(value: unknown): Promise<string> {
  return hash(JSON.stringify(value));
}

function hash(value: string | Uint8Array): string {
  return createHash("sha256").update(value).digest("hex").slice(0, 16);
}
