name: Documentation

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    uses: estifanos-sh/estifanos-sh/.github/workflows/validate-docs.yml@main
